name: Package and build release versions

on:
  push:
    tags:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取分支
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: 创建包
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}